### ISSUE TITLE
Can't install pylspci?

### ISSUE THREAD

**Issue by joaoherberto** [Ashark/davinci-resolve-checker#11]
I installed python-pip  first
then tried to install "pip install pylspsci" and I get the error:
```
 Z420$ pip install pylspci
Traceback (most recent call last):
  File "/usr/bin/pip", line 33, in <module>
    sys.exit(load_entry_point('pip==20.3b1', 'console_scripts', 'pip')())
  File "/usr/bin/pip", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: pip
```

**Comment by Ashark** [comment]
Works for me. I have python-pip 20.2.4-1.
