### ISSUE TITLE
Command 'expac -Qs '%n' opencl-driver' returned non-zero

### ISSUE THREAD

**Issue by rscm** [Ashark/davinci-resolve-checker#25]
## Steps I took to install
git clone https://github.com/Ashark/davinci-resolve-checker.git
```
sudo pacman -S expac mesa-demos python-distro
```
_(needed by the installation of python-pylspci)_
```
sudo pamac install fakeroot
```
```
yay -S python-pylspci
```
 ## Running it using NVIDIA GPU - dGPU
 ### $ prime-run ./davinci-resolve-checker.py
```
Locale unavailable: es_CL, using en_US instead
Using locale en_US
DaVinci Resolve checker 2.4.1
Installed DaVinci Resolve package: 
Traceback (most recent call last):
  File "/home/rscm/git/davinci-resolve-checker/./davinci-resolve-checker.py", line 79, in <module>
    installed_opencl_drivers = subprocess.check_output("expac -Qs '%n' opencl-driver", shell=True, text=True).splitlines()
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'expac -Qs '%n' opencl-driver' returned non-zero exit status 1.
```
 ## Running it using AMD GPU - iGPU
 ### $ ./davinci-resolve-checker.py
```
Locale unavailable: es_CL, using en_US instead
Using locale en_US
DaVinci Resolve checker 2.4.1
Installed DaVinci Resolve package: 
Traceback (most recent call last):
  File "/home/rscm/git/davinci-resolve-checker/./davinci-resolve-checker.py", line 79, in <module>
    installed_opencl_drivers = subprocess.check_output("expac -Qs '%n' opencl-driver", shell=True, text=True).splitlines()
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'expac -Qs '%n' opencl-driver' returned non-zero exit status 1.
```

 ## System
 ### inxi -sZb
```
System:    Host: legion Kernel: 5.15.2-2-MANJARO x86_64 bits: 64 Desktop: KDE Plasma 5.23.3 Distro: Manjaro Linux
Machine:   Type: Laptop System: LENOVO product: 82B1 v: Lenovo Legion 5 15ARH05H serial: <superuser required>
           Mobo: LENOVO model: LNVNB161216 v: SDK0R33126 WIN serial: <superuser required> UEFI: LENOVO v: FSCN14WW
           date: 08/26/2020
Battery:   ID-1: BAT0 charge: 49.1 Wh (60.0%) condition: 81.8/80.0 Wh (102.2%) volts: 15.3 min: 15.4
CPU:       Info: 8-Core AMD Ryzen 7 4800H with Radeon Graphics [MT MCP] speed: 1658 MHz min/max: 1400/2900 MHz
Graphics:  Device-1: NVIDIA TU106M [GeForce RTX 2060 Mobile] driver: nvidia v: 495.44
           Device-2: Advanced Micro Devices [AMD/ATI] Renoir driver: amdgpu v: kernel
           Device-3: Chicony Integrated Camera type: USB driver: uvcvideo
           Display: x11 server: X.Org 1.21.1.1 driver: loaded: amdgpu,ati,nvidia unloaded: modesetting,nouveau
           s-res: 1920x1080
           OpenGL: renderer: AMD RENOIR (DRM 3.42.0 5.15.2-2-MANJARO LLVM 13.0.0) v: 4.6 Mesa 21.2.5
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169
           Device-2: Intel Wi-Fi 6 AX200 driver: iwlwifi
Drives:    Local Storage: total: 476.94 GiB used: 232.31 GiB (48.7%)
Sensors:   Message: No sensor data found. Is lm-sensors configured?
Info:      Processes: 366 Uptime: 1d 3h 19m Memory: 15.01 GiB used: 3.87 GiB (25.8%) Shell: Bash inxi: 3.3.09
```

 ### python --version
```
Python 3.9.7
```

**Comment by Abdulee** [comment]
I am having the same error.. While running this
